nohup: ignoring input
original problem has 11923 variables (11923 bin, 0 int, 0 impl, 0 cont) and 15151 constraints
arithmetic
total time limit: 600
node time limit: 10
setcovering-small
firstsol
asymmetric
seed: 100
cpu
setcovering-large
firstsol
asymmetric
seed: 100
cpu
setcovering-small
rootsol
asymmetric
seed: 100
cpu
setcovering-large
rootsol
asymmetric
seed: 100
cpu
independentset-small
firstsol
symmetric
seed: 100
cpu
independentset-large
firstsol
symmetric
seed: 100
cpu
independentset-small
rootsol
symmetric
seed: 100
cpu
independentset-large
rootsol
symmetric
seed: 100
cpu
combinatorialauction-small
firstsol
symmetric
seed: 100
cpu
combinatorialauction-large
firstsol
symmetric
seed: 100
cpu
combinatorialauction-small
rootsol
symmetric
seed: 100
cpu
combinatorialauction-large
rootsol
symmetric
seed: 100
cpu
generalized_independentset-small
firstsol
symmetric
seed: 100
cpu
arithmetic
Traceback (most recent call last):
  File "compute_evaluation_results.py", line 91, in <module>
    reinforce_localbranch.primal_gap_integral_hybrid_03(test_instance_size=instance_size,
  File "/home/mpc-linux-01/projects/ML4LB/mllocalbranch_fromfiles.py", line 10408, in primal_gap_integral_hybrid_03
    with gzip.open(filename, 'rb') as f:
  File "/home/mpc-linux-01/opt/python3.8.0/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/mpc-linux-01/opt/python3.8.0/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './result/generated_instances/generalized_independentset/-small/symmetric/firstsol/rl/reinforce/test/old_models/evaluation-reinforce4lb-from-firstsol-t_node10s-t_total600s-small/rlactive_t_node_baseline-rlpolicy-treward1/seed120/lb-test-generalized_independentset-80_transformed.pkl'
